### PR TITLE
Fix github url strings (org edx -> openedx)

### PR DESCRIPTION
**Pull request by sarina**
## This PR was autogenerated

This pr replaces the old GitHub organization, github.com/edx, with the new GitHub organization, github.com/openedx.

Ref: openedx/tcril-engineering#42

### CODE REVIEW

**Review by DawoudSheraz — APPROVED** [review]
This is TNL area, but since the changes looks good, I am giving a 👍🏽

**Comment by sarina** [comment]
@DawoudSheraz the merge to master failed its build for a reason unrelated to me: https://github.com/openedx/studio-frontend/actions/runs/3068100781/jobs/4955145980

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/deploy-storybook-ci - Not found
npm ERR! 404 
npm ERR! 404  'deploy-storybook-ci@latest' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by DawoudSheraz** [comment]
I am sharing that with TNL so they can take a look.

**Comment by rayzhou-bit** [comment]
It looks like this build issue has been around for awhile. I'll see about getting a fix in.

**Pull request merged**
